FROM pypy:latest

ENV JSON_PATH="/var/log/nDPIdsrvd.json" \
    SHOW_PACKET_EVENTS=False \
    SHOW_FLOW_EVENTS=True \
    SHOW_ERROR_EVENTS=False \
    SHOW_DAEMON_EVENTS=False \
    UNIX="" \
    PORT=7000 \
    HOST=""

WORKDIR /usr/src/app

COPY py-json-stdout.py .
COPY nDPIsrvd.py .

CMD [ "pypy3", "-u", "./py-json-stdout.py"]
