services:
  producer:
    image: stefan96/heidpi-producer:latest
    container_name: heidpi_producer
    network_mode: host
    security_opt:
      - no-new-privileges
#    pids_limit: 8192
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32G
    environment:
      - HOSTNAME=test
      - TUNE_PARAM=max-reader-threads=4,max-flows-per-thread=65536,max-idle-flows-per-thread=2048,daemon-status-interval=15000000,flow-scan-interval=15000000,generic-max-idle-time=15000001,icmp-max-idle-time=15000001,udp-max-idle-time=15000001,tcp-max-idle-time=15000001,tcp-max-post-end-flow-time=5000000
      - MAX_BUFFERED_LINES=32768
      - JA3_URL=https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv
      - SSL_SHA1_URL=https://sslbl.abuse.ch/blacklist/sslblacklist.csv

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    #image: stefan96/heidpi-consumer:latest
    container_name: heidpi_consumer
    volumes:
      - ./heidpi-logs:/var/log/:rw
      - ./config.yml:/usr/src/app/config.yml:ro
    network_mode: host
    security_opt:
      - no-new-privileges
#    pids_limit: 8192
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    depends_on:
      - producer
    environment:
      - SHOW_DAEMON_EVENTS=1
      - SHOW_PACKET_EVENTS=1
      - SHOW_ERROR_EVENTS=1
      - SHOW_FLOW_EVENTS=1
