{
 "title": "heiDPI",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flow_id",
    "label": "Flow ID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Count Flows by Breed Type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (ndpi_breed) (rate({filename=\"/tmp/heidpi-logs/flow_event.json\"} |= `` | json | ndpi_breed != \"\" [1h]))"
    }
   ]
  },
  {
   "title": "Flow Events TIme Plot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (ndpi_breed) (rate({filename=\"/tmp/heidpi-logs/flow_event.json\"} |= `` | json | ndpi_breed != \"\" [1h]))"
    }
   ]
  },
  {
   "title": "Unsafe & Tracking Flows",
   "type": "logs",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/tmp/heidpi-logs/flow_event.json\"} |= `` | json | label_format flow_id=\"{{.flow_id}}\" | ndpi_breed=\"Tracker/Ads\" or ndpi_breed=\"Unsafe\" | line_format \"{{.flow_id}}\""
    }
   ]
  },
  {
   "title": "Potentially Dangerous & Dangerous Flows",
   "type": "logs",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/tmp/heidpi-logs/flow_event.json\"} |= `` | json | label_format flow_id=\"{{.flow_id}}\" | ndpi_breed=\"Dangerous\" or ndpi_breed=\"Potentially Dangerous\" | line_format \"{{.flow_id}}\""
    }
   ]
  },
  {
   "title": "Unrated Flows",
   "type": "logs",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/tmp/heidpi-logs/flow_event.json\"} |= `` | json | label_format flow_id=\"{{.flow_id}}\" | ndpi_breed=\"Unrated\" | line_format \"{{.flow_id}}\""
    }
   ]
  },
  {
   "title": " Flow Informations (Choose FlowID)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Flow Events Json",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/tmp/heidpi-logs/flow_event.json\"} | json | flow_id = `$flow_id`"
    }
   ]
  },
  {
   "title": "Flow ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "L4-Proto",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Current Flow State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Last Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Category",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Breed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Risk Confidence",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Destination IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Destination Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  },
  {
   "title": "Source IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 19 }
   ]
  }
 ]
}